name: Upgpkg V2ray SPEC Version
on: 
  workflow_dispatch:
  push:
    branches:
      - v2ray
  schedule:
    - cron: '0 0 */1 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: v2ray

      - name: Get Current Version
        run: |
          CURRENT_VERSION=`grep -E '^Version:' *.spec | awk '{print $2}'`
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV

      - name: Export latest v2ray version
        run: |
          NEW_VERSION=`curl -s https://api.github.com/repos/v2fly/v2ray-core/tags | jq -r .[0].name | sed 's/v//g'`
          if [ -z "$NEW_VERSION" ] || [ "$NEW_VERSION" = "null" ] ; then
            echo "NEW_VERSION is empty, stopping the workflow"
            exit 1
          fi
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Run rpmdev-bumpspec action
        if: ${{ env.CURRENT_VERSION != env.NEW_VERSION }}
        uses: netoarmando/rpmdev-bumpspec-action@v1
        with: 
          specfile: 'v2ray.spec'
          new: ${{ env.NEW_VERSION }}
          userstring: "zhullyb <zhullyb@outlook.com>"

      - name: Commit changes
        if: ${{ env.CURRENT_VERSION != env.NEW_VERSION }}
        run: |
          git config --local user.email "zhullyb@outlook.com"
          git config --local user.name "zhullyb"
          git add .
          git commit -m "upgpkg: v2ray@${{ env.NEW_VERSION }}"
          git push

      - name: trigger copr webhook
        if: ${{ env.CURRENT_VERSION != env.NEW_VERSION }}
        run: |
          curl -X POST ${{ secrets.COPR_HOOK_URL }}v2ray/
